### ISSUE TITLE
Use `interface` declarations instead of `type`

### ISSUE THREAD

**Issue by Shraymonks** [Shraymonks/flow-interfaces-chrome#4]
Though it has no effect on the flow types themselves, it probably makes more semantic sense to declare the top level chrome APIs through `interface` instead of `type`

**Comment by ssorallen** [comment]
I'm still unclear on when to use `interface` vs. `type`. Goldman's advice seems pertinent here: https://stackoverflow.com/a/36960529/368697

For these Chrome APIs, it seems like an argument for either way makes sense. Unless there's a clear advantage to switching to `interface`, this doesn't seem worth pursuing.
