### ISSUE TITLE
Why is chrome.windows.create typed like this?

### ISSUE THREAD

**Issue by callumlocke** [Shraymonks/flow-interfaces-chrome#8]
On [this line](https://github.com/Shraymonks/flow-interfaces-chrome/blob/ec9f55e789c1ae3bbdd44b043030f82d3a8aaa23/interfaces/windows.js#L37) that types the callback for `chrome.windows.create`:

```js
  }, callback?: (window?: chrome$Window) => void): void,
```

Why does `window?` have a question mark, i.e. why is it optional? Are there circumstances where windows.create will call back with nothing?

**Comment by Shraymonks** [comment]
I'm not sure if the callback is ever called with nothing, but according to the docs (https://developer.chrome.com/extensions/windows#method-create) it's optional
